/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { Turno } from '../model/turno';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class TurnoControllerService {

    protected basePath = '//pruebaservi.herokuapp.com';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * createTurno
     * 
     * @param body turno
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createTurnoUsingPOST(body: Turno, observe?: 'body', reportProgress?: boolean): Observable<Turno>;
    public createTurnoUsingPOST(body: Turno, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Turno>>;
    public createTurnoUsingPOST(body: Turno, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Turno>>;
    public createTurnoUsingPOST(body: Turno, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling createTurnoUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Turno>('post',`${this.basePath}/turno/create`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * deleteTurno
     * 
     * @param id id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteTurnoUsingDELETE(id: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteTurnoUsingDELETE(id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteTurnoUsingDELETE(id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteTurnoUsingDELETE(id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling deleteTurnoUsingDELETE.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('delete',`${this.basePath}/turno/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * findDisponible
     * 
     * @param fecha fecha
     * @param hora hora
     * @param servicioId servicioId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public findDisponibleUsingGET(fecha: string, hora?: string, servicioId?: string, observe?: 'body', reportProgress?: boolean): Observable<boolean>;
    public findDisponibleUsingGET(fecha: string, hora?: string, servicioId?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<boolean>>;
    public findDisponibleUsingGET(fecha: string, hora?: string, servicioId?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<boolean>>;
    public findDisponibleUsingGET(fecha: string, hora?: string, servicioId?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (fecha === null || fecha === undefined) {
            throw new Error('Required parameter fecha was null or undefined when calling findDisponibleUsingGET.');
        }



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (hora !== undefined && hora !== null) {
            queryParameters = queryParameters.set('hora', <any>hora);
        }
        if (servicioId !== undefined && servicioId !== null) {
            queryParameters = queryParameters.set('servicioId', <any>servicioId);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<boolean>('get',`${this.basePath}/turno/${encodeURIComponent(String(servicioId))}/${encodeURIComponent(String(fecha))}/${encodeURIComponent(String(hora))}`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * findId
     * 
     * @param id id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public findIdUsingGET1(id: string, observe?: 'body', reportProgress?: boolean): Observable<Turno>;
    public findIdUsingGET1(id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Turno>>;
    public findIdUsingGET1(id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Turno>>;
    public findIdUsingGET1(id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling findIdUsingGET1.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Turno>('get',`${this.basePath}/turno/findById/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * findTurnosPersona
     * 
     * @param personaId personaId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public findTurnosPersonaUsingGET(personaId: string, observe?: 'body', reportProgress?: boolean): Observable<Array<Turno>>;
    public findTurnosPersonaUsingGET(personaId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Turno>>>;
    public findTurnosPersonaUsingGET(personaId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Turno>>>;
    public findTurnosPersonaUsingGET(personaId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (personaId === null || personaId === undefined) {
            throw new Error('Required parameter personaId was null or undefined when calling findTurnosPersonaUsingGET.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<Turno>>('get',`${this.basePath}/turno/persona/${encodeURIComponent(String(personaId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * findTurnos
     * 
     * @param servicioId servicioId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public findTurnosUsingGET(servicioId: string, observe?: 'body', reportProgress?: boolean): Observable<Array<Turno>>;
    public findTurnosUsingGET(servicioId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Turno>>>;
    public findTurnosUsingGET(servicioId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Turno>>>;
    public findTurnosUsingGET(servicioId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (servicioId === null || servicioId === undefined) {
            throw new Error('Required parameter servicioId was null or undefined when calling findTurnosUsingGET.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<Turno>>('get',`${this.basePath}/turno/${encodeURIComponent(String(servicioId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * updateTurno
     * 
     * @param body turno
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateTurnoUsingPUT(body: Turno, observe?: 'body', reportProgress?: boolean): Observable<Turno>;
    public updateTurnoUsingPUT(body: Turno, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Turno>>;
    public updateTurnoUsingPUT(body: Turno, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Turno>>;
    public updateTurnoUsingPUT(body: Turno, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling updateTurnoUsingPUT.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Turno>('put',`${this.basePath}/turno/update`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
