/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Servicio { 
    descripcion?: string;
    empresaId?: string;
    foto?: string;
    id?: string;
    nombre?: string;
    precio?: number;
}